---
Name: goldfinch-component-products
---
Goldfinch\Component\Products\Admin\ProductsAdmin:
  extensions:
    - Goldfinch\Helpers\Extensions\BlocksAdminExtension

Goldfinch\Component\Products\Blocks\ProductsBlock:
  extensions:
    - Goldfinch\Helpers\Extensions\BaseElementExtension
---
Name: goldfinch-component-products-icon
Only:
  moduleexists: "goldfinch/enchantment"
---
Goldfinch\Component\Products\Admin\ProductsAdmin:
  menu_icon_class: "bi-box2-fill"

Goldfinch\Component\Products\Pages\Nest\Products:
  icon_class: "bi-box2-fill"

Goldfinch\Component\Products\Pages\Nest\ProductsByCategory:
  icon_class: "bi-box2"

Goldfinch\Component\Products\Blocks\ProductsBlock:
  icon: "bi-box2-fill"
